# -*- coding: utf-8 -*-
"""PropertyTax.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wmvaVVLMT0MQLuE2033oTBBtw599ZHoW

# PropertyTax Training and Model Selection

This notebook cleans the PropertyTax dataset, builds a classification-ready training table, compares several models, tunes the best one, and saves the final artifacts.

The training target is `is_late_payment` because `tax_amount` is almost fully determined by `assessed_value * tax_rate` in this dataset.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install matplotlib numpy pandas seaborn scikit-learn

import json
from pathlib import Path

import joblib
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import logging
import traceback
import warnings
import argparse
import sys
import os
import random

from sklearn.compose import ColumnTransformer
from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    ConfusionMatrixDisplay,
    accuracy_score,
    classification_report,
    f1_score,
    precision_recall_curve,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
)
from sklearn.model_selection import GridSearchCV, cross_val_score, train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

try:
    from scipy.special import expit
except Exception:
    expit = None

sns.set_theme(style='whitegrid')
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:,.4f}'.format)

# Use robust repo-relative paths (works when running from project root)
BASE = Path(__file__).resolve().parent.parent
DATA_DIR = BASE / "datasets"
RAW_PATH = DATA_DIR / "PropertyTax.csv"
CLEAN_PATH = DATA_DIR / "PropertyTax_cleaned.csv"
PROCESSED_PATH = DATA_DIR / "PropertyTax_model_ready.csv"
ARTIFACTS_DIR = BASE / "models"
ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)

# Logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

# Global exception hook to capture unhandled tracebacks into artifacts directory
import sys as _sys

def _write_traceback_and_exit(exc_info):
    try:
        trace_path = ARTIFACTS_DIR / 'propertytax_retrain_traceback.txt'
        with trace_path.open('w', encoding='utf-8') as f:
            traceback.print_exception(*exc_info, file=f)
        logging.error('An unhandled exception occurred. Traceback written to %s', trace_path)
    except Exception:
        logging.exception('Failed to write traceback file')

def _excepthook(exc_type, exc_value, exc_tb):
    _write_traceback_and_exit((exc_type, exc_value, exc_tb))
    return _sys.__excepthook__(exc_type, exc_value, exc_tb)

_sys.excepthook = _excepthook


def make_onehot():
    """Return a OneHotEncoder configured to output dense arrays (compatible across sklearn versions)."""
    try:
        return OneHotEncoder(handle_unknown="ignore", sparse_output=False)
    except TypeError:
        return OneHotEncoder(handle_unknown="ignore", sparse=False)


def _safe_predict_proba(pipeline, X):
    """Return probability estimates for the positive class if possible, else None."""
    try:
        probs = pipeline.predict_proba(X)
        if getattr(probs, "ndim", 0) == 2 and probs.shape[1] >= 2:
            return probs[:, 1]
        return probs.ravel()
    except Exception:
        try:
            scores = pipeline.decision_function(X)
            if expit is not None:
                return expit(scores)
            s = np.asarray(scores, dtype=float)
            smin, smax = s.min(), s.max()
            if smax > smin:
                return (s - smin) / (smax - smin)
            return None
        except Exception:
            return None


def compute_metrics(y_true, y_pred, y_prob):
    """Compute a consistent set of metrics and return JSON-serializable values.

    Returns a dict with keys: accuracy, precision, recall, f1Score, rocAuc (None when not computable).
    Values are rounded to 4 decimals and are native Python floats or None.
    """
    try:
        acc = float(accuracy_score(y_true, y_pred))
    except Exception:
        acc = float('nan')

    if len(np.unique(y_true)) > 1 and y_prob is not None:
        try:
            prec = float(precision_score(y_true, y_pred, zero_division=0))
        except Exception:
            prec = float('nan')
        try:
            rec = float(recall_score(y_true, y_pred, zero_division=0))
        except Exception:
            rec = float('nan')
        try:
            f1 = float(f1_score(y_true, y_pred, zero_division=0))
        except Exception:
            f1 = float('nan')
        try:
            auc = float(roc_auc_score(y_true, y_prob))
        except Exception:
            auc = None
    else:
        # Single-class or missing probabilities: derive precision/recall/f1 conservatively
        if np.all(y_pred == y_true):
            prec = rec = f1 = 1.0
        else:
            prec = rec = f1 = 0.0
        auc = None

    def _safe_round(v):
        if v is None:
            return None
        try:
            if np.isnan(v):
                return None
        except Exception:
            pass
        return round(float(v), 4)

    return {
        'accuracy': _safe_round(acc),
        'precision': _safe_round(prec),
        'recall': _safe_round(rec),
        'f1Score': _safe_round(f1),
        'rocAuc': _safe_round(auc),
    }


def _save_metrics_and_plots(y_true, y_pred, y_prob, model_display_name: str, out_dir: Path, prefix: str | None = None):
    """Save ROC/PR/metric stat card images and return the computed metrics and paths.

    The `prefix` (usually dataset stem) will be prepended to generated filenames when provided.
    """
    out_dir.mkdir(parents=True, exist_ok=True)

    metrics = compute_metrics(y_true, y_pred, y_prob)

    model_slug = model_display_name.lower().replace(' ', '_')
    if prefix:
        base_name = f"{prefix}_{model_slug}"
    else:
        base_name = model_slug

    roc_path = out_dir / f"{base_name}_roc.png"
    pr_path = out_dir / f"{base_name}_pr.png"
    stat_path = out_dir / f"{base_name}_metrics.png"

    # ROC + PR
    if y_prob is not None and len(np.unique(y_true)) > 1:
        try:
            fpr, tpr, _ = roc_curve(y_true, y_prob)
            fig = plt.figure(figsize=(6, 5))
            auc_label = f"AUC = {metrics['rocAuc']:.3f}" if metrics.get('rocAuc') is not None else 'AUC = n/a'
            plt.plot(fpr, tpr, label=auc_label)
            plt.plot([0, 1], [0, 1], linestyle='--', color='gray')
            plt.xlabel('False Positive Rate')
            plt.ylabel('True Positive Rate')
            plt.title(f'ROC Curve - {model_display_name}')
            plt.legend()
            fig.savefig(roc_path, bbox_inches='tight', dpi=150)
            plt.close(fig)

            precision_vals, recall_vals, _ = precision_recall_curve(y_true, y_prob)
            fig = plt.figure(figsize=(6, 5))
            plt.plot(recall_vals, precision_vals, color='darkorange')
            plt.xlabel('Recall')
            plt.ylabel('Precision')
            plt.title(f'Precision-Recall - {model_display_name}')
            fig.savefig(pr_path, bbox_inches='tight', dpi=150)
            plt.close(fig)
        except Exception:
            logging.exception('Failed to plot ROC/PR for %s', model_display_name)

    # Stat card image
    try:
        fig = plt.figure(figsize=(4, 3))
        plt.axis('off')

        def _fmt(v):
            try:
                if v is None:
                    return 'n/a'
                if isinstance(v, float) and np.isnan(v):
                    return 'n/a'
                return f"{v:.4f}"
            except Exception:
                return str(v)

        text = (
            f"Model: {model_display_name}\n"
            f"Accuracy: {_fmt(metrics.get('accuracy'))}\n"
            f"Precision: {_fmt(metrics.get('precision'))}\n"
            f"Recall: {_fmt(metrics.get('recall'))}\n"
            f"F1: {_fmt(metrics.get('f1Score'))}\n"
            f"ROC AUC: {_fmt(metrics.get('rocAuc'))}\n"
        )
        plt.text(0.01, 0.98, text, va='top', fontsize=10, family='monospace')
        fig.savefig(stat_path, bbox_inches='tight', dpi=150)
        plt.close(fig)
    except Exception:
        logging.exception('Failed to render stat card for %s', model_display_name)

    return metrics, {"roc": str(roc_path) if roc_path.exists() else None, "pr": str(pr_path) if pr_path.exists() else None, "stat": str(stat_path) if stat_path.exists() else None}


def normalize_title_case(series):
    cleaned = series.fillna('').astype(str).str.replace('-', ' ', regex=False)
    cleaned = cleaned.str.split().str.join(' ')
    return cleaned.str.title()


def clean_property_tax_dataset(frame):
    cleaned = frame.copy()
    # Deduplicate by record_id when present, otherwise dedupe whole rows
    if 'record_id' in cleaned.columns:
        cleaned = cleaned.drop_duplicates(subset=['record_id'], keep='first').copy()
    else:
        cleaned = cleaned.drop_duplicates().copy()

    if 'province' in cleaned.columns:
        try:
            cleaned['province'] = normalize_title_case(cleaned['province'])
        except Exception:
            logging.exception('Failed to normalize province')

    if 'property_type' in cleaned.columns:
        try:
            cleaned['property_type'] = normalize_title_case(cleaned['property_type'])
        except Exception:
            logging.exception('Failed to normalize property_type')

    if 'unit_no' in cleaned.columns:
        try:
            unit_no = cleaned['unit_no'].fillna('').astype(str).str.strip()
            cleaned['unit_no'] = unit_no.mask(unit_no.eq('') | unit_no.str.lower().eq('nan'), 'N/A')
        except Exception:
            logging.exception('Failed to clean unit_no')

    return cleaned


def find_dataset(cli_path: str | None = None) -> Path:
    """Find a reasonable CSV to use as the dataset.

    Priority: explicit CLI path > filename contains 'model_ready' > filename contains 'propertytax' > contains target column > largest CSV.
    """
    if cli_path:
        p = Path(cli_path)
        if p.exists():
            return p
        raise FileNotFoundError(f"Dataset {cli_path} not found")

    candidates = list(DATA_DIR.glob('*.csv'))
    # include nested csvs if none at top-level
    if not candidates:
        candidates = list(DATA_DIR.rglob('*.csv')) + list(BASE.rglob('*.csv'))
    if not candidates:
        raise FileNotFoundError('No CSV datasets found under datasets/ or workspace')

    # prefer filenames
    for c in candidates:
        if 'model_ready' in c.name.lower():
            return c
    for c in candidates:
        if 'propertytax' in c.name.lower():
            return c

    # prefer files containing the target column
    for c in candidates:
        try:
            cols = pd.read_csv(c, nrows=5, low_memory=False).columns.tolist()
            if 'is_late_payment' in cols:
                return c
        except Exception:
            continue

    # fallback: largest CSV by size
    return max(candidates, key=lambda p: p.stat().st_size)


def _save_fig(fig, name: str):
    path = ARTIFACTS_DIR / name
    try:
        fig.tight_layout()
    except Exception:
        pass
    fig.savefig(path)
    plt.close(fig)
    logging.info('Saved figure: %s', path)


def main(dataset_cli: str | None = None):
    try:
        dataset_path = find_dataset(dataset_cli)
        logging.info('Using dataset: %s', dataset_path)

        # Make runs deterministic where possible
        np.random.seed(42)
        random.seed(42)
        os.environ.setdefault('PYTHONHASHSEED', '0')

        cleaned_path = dataset_path.parent / f"{dataset_path.stem}_cleaned.csv"
        processed_path = dataset_path.parent / f"{dataset_path.stem}_model_ready.csv"

        df_raw = pd.read_csv(dataset_path, low_memory=False)
        df = clean_property_tax_dataset(df_raw)
        df.to_csv(cleaned_path, index=False)

        logging.info('Raw rows: %s', len(df_raw))
        logging.info('Rows after duplicate removal: %s', len(df))
        logging.info('Duplicates removed: %s', len(df_raw) - len(df))

        # Basic checks and safe column derivations
        if 'tax_amount' in df.columns and 'assessed_value' in df.columns and 'tax_rate' in df.columns:
            formula_gap = (df['tax_amount'] - (df['assessed_value'] * df['tax_rate'])).abs()
            logging.info('Tax formula gap - max: %s mean: %s', formula_gap.max(), formula_gap.mean())

        # Target handling: prefer existing 'is_late_payment', otherwise try to infer a binary column
        if 'is_late_payment' not in df.columns:
            # attempt inference: find a column with only 0/1 or boolean-like values
            inferred = None
            for c in df.columns:
                try:
                    vals = pd.Series(df[c].dropna().unique())
                    if set(vals.astype(str)).issubset({'0', '1', '0.0', '1.0', 'True', 'False', 'true', 'false'}):
                        inferred = c
                        break
                except Exception:
                    continue
            if inferred:
                logging.info('Inferred target column: %s', inferred)
                df.rename(columns={inferred: 'is_late_payment'}, inplace=True)
            else:
                raise ValueError('No target column "is_late_payment" found or inferred')

        # safe datetime / derived logs
        if 'due_date' in df.columns:
            df['due_date'] = pd.to_datetime(df['due_date'], errors='coerce')
            df['due_month'] = df['due_date'].dt.month
            df['due_quarter'] = df['due_date'].dt.quarter
        if 'market_value' in df.columns:
            df['log_market_value'] = np.log1p(df['market_value'].astype(float))
        if 'assessed_value' in df.columns:
            df['log_assessed_value'] = np.log1p(df['assessed_value'].astype(float))
        if 'outstanding_balance' in df.columns:
            df['log_outstanding_balance'] = np.log1p(df['outstanding_balance'].astype(float))

        # drop obvious identifier/privacy columns if present
        drop_columns = [
            'record_id',
            'owner_id',
            'owner_name',
            'tin',
            'mailing_address',
            'property_id',
            'pin',
            'tax_declaration_no',
            'property_address',
            'lot_number',
            'due_date',
        ]
        drop_columns = [c for c in drop_columns if c in df.columns]
        model_df = df.drop(columns=drop_columns).copy()
        model_df['is_late_payment'] = model_df['is_late_payment'].astype(int)

        # Detect & drop perfect-mapping columns (leakage)
        try:
            target = 'is_late_payment'
            candidate_cols = [c for c in model_df.columns if c != target]
            perfect_cols = []
            for c in candidate_cols:
                try:
                    groups = model_df.groupby(c)[target].nunique()
                    if len(groups) > 0 and groups.max() == 1:
                        perfect_cols.append(c)
                except Exception:
                    continue
            if perfect_cols:
                logging.warning('Dropping perfect-mapping columns likely causing leakage: %s', perfect_cols)
                debug_path = ARTIFACTS_DIR / 'dropped_leaky_columns.json'
                debug_path.write_text(json.dumps({'dropped': perfect_cols}, indent=2), encoding='utf-8')
                model_df = model_df.drop(columns=perfect_cols)
        except Exception:
            logging.exception('Failed while detecting/dropping perfect-mapping features')

        model_df.to_csv(processed_path, index=False)
        logging.info('Processed dataset saved to %s', processed_path)

        # Exploratory plots (save to artifacts)
        try:
            fig, axes = plt.subplots(2, 2, figsize=(16, 12))
            if 'is_late_payment' in model_df.columns:
                sns.countplot(data=model_df, x='is_late_payment', ax=axes[0, 0])
                axes[0, 0].set_title('Target Distribution')
            if 'property_type' in model_df.columns:
                late_rate_by_type = model_df.groupby('property_type')['is_late_payment'].mean().sort_values(ascending=False)
                sns.barplot(x=late_rate_by_type.values, y=late_rate_by_type.index, ax=axes[0, 1], color='steelblue')
                axes[0, 1].set_title('Late Payment Rate by Property Type')
            if 'payment_compliance_score' in model_df.columns and 'is_late_payment' in model_df.columns:
                sns.histplot(data=model_df, x='payment_compliance_score', hue='is_late_payment', bins=30, kde=True, ax=axes[1, 0], element='step', stat='density', common_norm=False)
                axes[1, 0].set_title('Payment Compliance Score by Target')
            if 'avg_previous_delay_days' in model_df.columns and 'is_late_payment' in model_df.columns:
                sns.boxplot(data=model_df, x='is_late_payment', y='avg_previous_delay_days', ax=axes[1, 1])
                axes[1, 1].set_title('Average Previous Delay Days by Target')
            _save_fig(fig, f"{dataset_path.stem}_exploratory_overview.png")
        except Exception:
            logging.exception('Failed to produce exploratory plots')

        # Correlation heatmap
        try:
            corr_columns = [
                'market_value',
                'assessed_value',
                'tax_amount',
                'years_as_owner',
                'prior_late_payments',
                'prior_unpaid_payments',
                'avg_previous_delay_days',
                'outstanding_balance',
                'payment_compliance_score',
                'is_late_payment',
            ]
            corr_columns = [c for c in corr_columns if c in model_df.columns]
            if len(corr_columns) >= 2:
                fig = plt.figure(figsize=(12, 8))
                sns.heatmap(model_df[corr_columns].corr(), annot=True, cmap='coolwarm', fmt='.2f')
                plt.title('Correlation Heatmap')
                _save_fig(fig, f"{dataset_path.stem}_correlation_heatmap.png")
        except Exception:
            logging.exception('Failed to produce correlation heatmap')

        # Pairplot
        try:
            pairplot_columns = [
                'payment_compliance_score',
                'prior_late_payments',
                'avg_previous_delay_days',
                'log_outstanding_balance',
                'is_late_payment',
            ]
            pairplot_columns = [c for c in pairplot_columns if c in model_df.columns]
            if len(pairplot_columns) >= 2:
                pairplot_sample = model_df[pairplot_columns].sample(n=min(400, len(model_df)), random_state=42).copy()
                if 'is_late_payment' in pairplot_sample.columns:
                    pairplot_sample['is_late_payment'] = pairplot_sample['is_late_payment'].map({0: 'On Time', 1: 'Late'})
                    g = sns.pairplot(pairplot_sample, hue='is_late_payment', corner=True, diag_kind='hist')
                    try:
                        g.savefig(ARTIFACTS_DIR / f"{dataset_path.stem}_pairplot.png")
                    except Exception:
                        logging.exception('Failed to save pairplot')
        except Exception:
            logging.exception('Failed to produce pairplot')

        # Prepare X/y and feature lists
        target_column = 'is_late_payment'
        if target_column not in model_df.columns:
            raise ValueError('Target column is missing after preprocessing')
        X = model_df.drop(columns=[target_column])
        y = model_df[target_column]

        categorical_features = X.select_dtypes(include=['object', 'string']).columns.tolist()
        numeric_features = X.select_dtypes(exclude=['object', 'string']).columns.tolist()

        # Fill numeric features that are entirely NaN to avoid SimpleImputer errors
        for col in numeric_features:
            if X[col].isna().all():
                logging.warning("Numeric feature '%s' has all-NaN values — filling with 0.0", col)
                X[col] = 0.0
                model_df[col] = model_df[col].fillna(0.0)

        # Require at least two classes in target
        if y.nunique() < 2:
            raise ValueError('Target has fewer than 2 classes; cannot train')

        # Split
        try:
            X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
        except Exception:
            X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

        numeric_transformer = Pipeline(steps=[('imputer', SimpleImputer(strategy='median')), ('scaler', StandardScaler()),])
        categorical_transformer = Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')), ('onehot', make_onehot()),])

        preprocess = ColumnTransformer(transformers=[('cat', categorical_transformer, categorical_features), ('num', numeric_transformer, numeric_features),])

        logging.info('Categorical features: %s', categorical_features)
        logging.info('Numeric features: %s', numeric_features)
        logging.info('X_train shape: %s', X_train.shape)
        logging.info('X_test shape: %s', X_test.shape)

        model_builders = {
            'Logistic Regression': lambda: LogisticRegression(max_iter=2000, class_weight='balanced'),
            'Random Forest': lambda: RandomForestClassifier(n_estimators=300, random_state=42, class_weight='balanced', n_jobs=-1),
            'Extra Trees': lambda: ExtraTreesClassifier(n_estimators=300, random_state=42, class_weight='balanced', n_jobs=-1),
        }

        baseline_results = []
        fitted_models = {}

        for model_name, model_builder in model_builders.items():
            pipeline = Pipeline(steps=[('preprocess', preprocess), ('model', model_builder()),])
            # cross-val only when both classes are present in y_train
            try:
                if y_train.nunique() >= 2:
                    cv_scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring='roc_auc', n_jobs=1)
                else:
                    cv_scores = [float('nan')]
            except Exception:
                logging.exception('CV scoring failed for %s', model_name)
                cv_scores = [float('nan')]

            try:
                pipeline.fit(X_train, y_train)
                y_pred = pipeline.predict(X_test)
                y_score = _safe_predict_proba(pipeline, X_test)
                metrics_dict = compute_metrics(y_test, y_pred, y_score)

                baseline_results.append({
                    'model': model_name,
                    'cv_roc_auc_mean': float(np.nanmean(cv_scores)),
                    'cv_roc_auc_std': float(np.nanstd(cv_scores)),
                    'test_accuracy': metrics_dict['accuracy'] if metrics_dict.get('accuracy') is not None else float('nan'),
                    'test_precision': metrics_dict['precision'] if metrics_dict.get('precision') is not None else float('nan'),
                    'test_recall': metrics_dict['recall'] if metrics_dict.get('recall') is not None else float('nan'),
                    'test_f1': metrics_dict['f1Score'] if metrics_dict.get('f1Score') is not None else float('nan'),
                    'test_roc_auc': metrics_dict['rocAuc'] if metrics_dict.get('rocAuc') is not None else float('nan'),
                })
                fitted_models[model_name] = pipeline
            except Exception:
                logging.exception('Training failed for baseline model %s', model_name)

        results_df = pd.DataFrame(baseline_results)
        if results_df.empty:
            logging.error('No baseline results were produced; attempting fallback logistic regression')
            # fallback single pipeline
            fallback_pipeline = Pipeline(steps=[('preprocess', preprocess), ('model', LogisticRegression(max_iter=2000, class_weight='balanced'))])
            fallback_pipeline.fit(X_train, y_train)
            y_pred_fb = fallback_pipeline.predict(X_test)
            y_score_fb = _safe_predict_proba(fallback_pipeline, X_test)
            fb_metrics = compute_metrics(y_test, y_pred_fb, y_score_fb)
            results_df = pd.DataFrame([{
                'model': 'Logistic Regression',
                'cv_roc_auc_mean': float('nan'),
                'cv_roc_auc_std': float('nan'),
                'test_accuracy': fb_metrics['accuracy'] if fb_metrics.get('accuracy') is not None else float('nan'),
                'test_precision': fb_metrics['precision'] if fb_metrics.get('precision') is not None else float('nan'),
                'test_recall': fb_metrics['recall'] if fb_metrics.get('recall') is not None else float('nan'),
                'test_f1': fb_metrics['f1Score'] if fb_metrics.get('f1Score') is not None else float('nan'),
                'test_roc_auc': fb_metrics['rocAuc'] if fb_metrics.get('rocAuc') is not None else float('nan'),
            }])
            fitted_models['Logistic Regression'] = fallback_pipeline

        results_df = results_df.sort_values(['test_roc_auc', 'test_f1', 'test_accuracy'], ascending=False,).reset_index(drop=True)

        best_model_name = results_df.loc[0, 'model']
        best_baseline_model = fitted_models[best_model_name]
        logging.info('Best baseline model: %s', best_model_name)

        # Plot baseline ROC curves
        try:
            fig = plt.figure(figsize=(10, 7))
            for model_name, pipeline in fitted_models.items():
                y_score = _safe_predict_proba(pipeline, X_test)
                if y_score is not None and len(np.unique(y_test)) > 1:
                    fpr, tpr, _ = roc_curve(y_test, y_score)
                    auc_score = roc_auc_score(y_test, y_score)
                    plt.plot(fpr, tpr, label=f'{model_name} (AUC={auc_score:.3f})')
            plt.plot([0, 1], [0, 1], linestyle='--', color='gray')
            plt.title('ROC Curves for Baseline Models')
            plt.xlabel('False Positive Rate')
            plt.ylabel('True Positive Rate')
            plt.legend()
            _save_fig(fig, f"{dataset_path.stem}_baseline_rocs.png")
        except Exception:
            logging.exception('Failed to plot baseline ROC curves')

        try:
            disp_fig = plt.figure()
            ConfusionMatrixDisplay.from_estimator(best_baseline_model, X_test, y_test, cmap='Blues')
            plt.title(f'Confusion Matrix - {best_model_name}')
            _save_fig(plt.gcf(), f"{dataset_path.stem}_baseline_confusion_{best_model_name.lower().replace(' ', '_')}.png")
        except Exception:
            logging.exception('Failed to plot baseline confusion matrix')

        # Hyperparameter search on best baseline model
        param_grids = {
            'Logistic Regression': {'model__C': [0.1, 1.0, 3.0], 'model__class_weight': [None, 'balanced'],},
            'Random Forest': {'model__n_estimators': [200, 400], 'model__max_depth': [None, 16], 'model__min_samples_split': [2, 8], 'model__min_samples_leaf': [1, 2], 'model__max_features': ['sqrt', 0.6],},
            'Extra Trees': {'model__n_estimators': [200, 400], 'model__max_depth': [None, 16], 'model__min_samples_split': [2, 8], 'model__min_samples_leaf': [1, 2], 'model__max_features': ['sqrt', 0.6],},
        }

        search_pipeline = Pipeline(steps=[('preprocess', preprocess), ('model', model_builders[best_model_name]()),])
        grid = GridSearchCV(estimator=search_pipeline, param_grid=param_grids[best_model_name], cv=5, scoring='roc_auc', n_jobs=1, verbose=0,)
        try:
            grid.fit(X_train, y_train)
            best_model = grid.best_estimator_
            grid_best_params = grid.best_params_
            grid_best_score = grid.best_score_
            logging.info('Best Params: %s', grid_best_params)
            logging.info('Best CV ROC AUC: %s', grid_best_score)
        except Exception:
            logging.exception('Grid search failed for %s; falling back to baseline model', best_model_name)
            best_model = best_baseline_model
            grid_best_params = getattr(grid, 'best_params_', {})
            grid_best_score = getattr(grid, 'best_score_', float('nan'))

        y_pred = best_model.predict(X_test)
        y_score = _safe_predict_proba(best_model, X_test)
        eval_metrics = compute_metrics(y_test, y_pred, y_score)
        logging.info('Test Accuracy: %s', eval_metrics['accuracy'])
        logging.info('Test Precision: %s', eval_metrics['precision'])
        logging.info('Test Recall: %s', eval_metrics['recall'])
        logging.info('Test F1: %s', eval_metrics['f1Score'])
        logging.info('Test ROC AUC: %s', eval_metrics['rocAuc'] if eval_metrics['rocAuc'] is not None else 'n/a')

        # Tuned model plots
        try:
            fig = plt.figure(figsize=(12, 5))
            ConfusionMatrixDisplay.from_predictions(y_test, y_pred, cmap='Blues')
            plt.title('Tuned Model Confusion Matrix')
            _save_fig(plt.gcf(), f"{dataset_path.stem}_tuned_confusion.png")
        except Exception:
            logging.exception('Failed to plot tuned confusion matrix')

        try:
            if y_score is not None and len(np.unique(y_test)) > 1:
                fig = plt.figure()
                fpr, tpr, _ = roc_curve(y_test, y_score)
                plt.plot(fpr, tpr, label=f'AUC = {roc_auc_score(y_test, y_score):.3f}')
                plt.plot([0, 1], [0, 1], linestyle='--', color='gray')
                plt.title('Tuned Model ROC Curve')
                _save_fig(fig, f"{dataset_path.stem}_tuned_roc.png")

                fig = plt.figure()
                precision_vals, recall_vals, _ = precision_recall_curve(y_test, y_score)
                plt.plot(recall_vals, precision_vals, color='darkorange')
                plt.title('Precision-Recall Curve')
                _save_fig(fig, f"{dataset_path.stem}_tuned_pr.png")
        except Exception:
            logging.exception('Failed to plot tuned ROC/PR')

        # Feature importance
        estimator = best_model.named_steps['model']
        try:
            feature_names = best_model.named_steps['preprocess'].get_feature_names_out()
        except Exception:
            # Fallback: reconstruct from transformers
            cat_cols = categorical_features
            num_cols = numeric_features
            ct = best_model.named_steps['preprocess']
            names = []
            if hasattr(ct, 'transformers_'):
                for name, trans, cols in ct.transformers_:
                    if name == 'cat':
                        try:
                            ohe = trans.named_steps.get('onehot')
                            cats = ohe.categories_
                            for col, cat_vals in zip(cols, cats):
                                names.extend([f"{col}__{v}" for v in cat_vals.astype(str)])
                        except Exception:
                            names.extend(cols)
                    elif name == 'num':
                        names.extend(cols)
            feature_names = np.array(names + list(num_cols))

        try:
            if hasattr(estimator, 'feature_importances_'):
                importance_values = np.asarray(estimator.feature_importances_)
            else:
                coef = np.asarray(estimator.coef_)
                if coef.ndim == 1:
                    importance_values = np.abs(coef)
                else:
                    importance_values = np.mean(np.abs(coef), axis=0)
        except Exception:
            importance_values = np.zeros(len(feature_names), dtype=float)

        if len(importance_values) != len(feature_names):
            if len(importance_values) < len(feature_names):
                pad = np.zeros(len(feature_names) - len(importance_values), dtype=float)
                importance_values = np.concatenate([importance_values, pad])
            else:
                importance_values = importance_values[: len(feature_names)]

        feature_importance_df = pd.DataFrame({'feature': feature_names, 'importance': importance_values}).sort_values('importance', ascending=False).reset_index(drop=True)
        try:
            fig = plt.figure(figsize=(10, 8))
            sns.barplot(data=feature_importance_df.head(15), x='importance', y='feature', color='steelblue')
            plt.title(f'Top 15 Features - {best_model_name}')
            _save_fig(fig, f"{dataset_path.stem}_feature_importance.png")
        except Exception:
            logging.exception('Failed to plot feature importances')

        selection_results_path = ARTIFACTS_DIR / 'propertytax_model_selection_results.csv'
        model_path = ARTIFACTS_DIR / f"{best_model_name.lower().replace(' ', '_')}_propertytax_model.pkl"
        feature_info_path = ARTIFACTS_DIR / 'propertytax_feature_info.json'

        results_df.to_csv(selection_results_path, index=False)
        joblib.dump(best_model, model_path)

        feature_info = {'target': target_column, 'best_model_name': best_model_name, 'categorical_features': categorical_features, 'numeric_features': numeric_features, 'all_features': list(X.columns), 'best_params': grid_best_params,}
        try:
            saved_metrics, saved_paths = _save_metrics_and_plots(y_test, y_pred, y_score, best_model_name, ARTIFACTS_DIR, prefix=dataset_path.stem)
            feature_info['best_model_metrics'] = saved_metrics
            feature_info['best_model_artifacts'] = saved_paths
        except Exception:
            logging.exception('Failed to save evaluation plots for best model')

        with feature_info_path.open('w', encoding='utf-8') as file:
            json.dump(feature_info, file, indent=4)

        logging.info('Model selection results saved to: %s', selection_results_path.resolve())
        logging.info('Best model saved to: %s', model_path.resolve())
        logging.info('Feature info saved to: %s', feature_info_path.resolve())

    except Exception:
        # ensure traceback is written
        _write_traceback_and_exit(sys.exc_info())
        raise


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Train and evaluate PropertyTax models')
    parser.add_argument('--dataset', type=str, default=None, help='Path to CSV dataset to use')
    args = parser.parse_args()
    main(args.dataset)